spring.application.name=EverStatus

# EverStatus Configuration
# Application Settings
everstatus.timer.interval=60000
everstatus.shutdown.delay=3000
everstatus.key.code=VK_F15

# UI Settings
everstatus.ui.window.width=800
everstatus.ui.window.height=550
everstatus.ui.theme.background.rgb=44,62,80
everstatus.ui.theme.panel.rgb=52,73,94
everstatus.ui.theme.light.rgb=236,240,241

# Logging Settings
logging.level.root=INFO
logging.level.com.automations.everstatus=DEBUG
